### ISSUE TITLE
[BUG]: Unable to update profile photo and bio in User Profile screen

### ISSUE THREAD

**Issue by yasht01** [CollActionteam/collaction_app#145] opened 2022-01-05 11:05 UTC
**Describe the bug**
App does not update profile photo and bio after clicking on `Save changes` button.

**To Reproduce**
1. Go to User Profile screen
2. Click on `Edit profile`
3. Add a new profile photo and bio
4. Click on `Save changes`
5. Relaunch the app or log out and log in again.

**Expected behavior**
New profile photo and bio should be displayed on the User Profile screen.

**Device information:**
 - Device: Nokia 6.1 Plus
 - OS: Android 10
 - Version + build number: 1.0.1 (389)

**Comment by rubenhorn** [comment] 2022-01-05 12:44
Updating the bio worked for me, but I the profile picture stays the same (maybe it was due to the content moderation... I will have to check the server logs)

**Comment by yasht01** [comment] 2022-01-05 19:43
I tested this again using the test number and updating profile picture works fine now. (Only thing it took some time to update it on the app)

**Comment by Xazin** [comment] 2022-01-05 20:54
I have tried multiple things, without success. On a test number as well.

**Comment by rubenhorn** [comment] 2022-01-06 07:44
@yasht01 so we can rule out any issues with the backend?

**Comment by sudo-saksham** [comment] 2022-01-06 08:06
@yasht01 For some reason, when I'm relaunching the app the profile photo isn't restored.

Also, I think if the user's profile is being updated/loaded there should be a loading spinner or something while the process is being executed. Otherwise, it shows Create a/c or sign in while it is leading which might confuse the user.
Any thoughts?? @Xazin @wizlif

**Comment by sudo-saksham** [comment] 2022-01-06 09:28
Update: It was restored but it takes some 5-10 seconds to update the profile photo. So, I think the issue is the duration of fetching profile photo. @Xazin @yasht01 @rubenhorn

**Comment by wizlif** [comment] 2022-01-06 09:34
Profile photos could be large, was there any image optimization done by the backend for profile photos.

**Comment by yasht01** [comment] 2022-01-06 09:49
Update: Updating the bio works fine but updating the profile picture is working sometimes. It worked for the first time with me but next two attempts did not. Same was the case with @sudo-saksham

**Comment by yasht01** [comment] 2022-01-06 14:37
While debugging the app I noticed that after uploading the image using PUT request successfully, the new profile picture is not updated on the `/profile-pictures` endpoint.

**Comment by rubenhorn** [comment] 2022-01-06 20:30
The app should enforce that the image is valid.
![image](https://user-images.githubusercontent.com/5367484/148446408-7af09559-d76d-4358-abd8-724e2c5262bc.png)

The following should be enforced in the app:
* < 5MB
* 250-1024px
* 1.0 aspect ratio

The user should maybe be notified that the image has been uploaded but will be moderated for content first. (pop-up)
Similarly, if the image does not match the requirements, this should be clearly indicated (pop-up)

**Comment by rubenhorn** [comment] 2022-01-06 20:38
We could resize the image to the preferred size regardless: https://stackoverflow.com/a/49701775

**Comment by rubenhorn** [comment] 2022-01-06 21:40
The issue of the image not updating is due to the use of the Cloudflare CDN.  
We will have to invalidate the cache on the backend when a new profile picture is updated.

For now, we could notify the user that it may take up to 24h to update the profile picture (in the same pop-up where we inform them about content moderation)

Thoughts?

**Comment by yasht01** [comment] 2022-01-07 09:39
For the first version, the pop-up workaround can be done if there is no quick fix for updating the profile picture.

**Comment by wizlif** [comment] 2022-01-07 09:41
How would that work ??

**Comment by wizlif** [comment] 2022-01-07 09:43
> For the first version, the pop-up workaround can be done if there is no quick fix for updating the profile picture.
> @Xazin @wizlif @sudo-saksham 

How would that work ??

**Comment by yasht01** [comment] 2022-01-07 09:45
On clicking the `Save Changes` button, a snack bar can be shown to notify the user that updating the picture can take some time. I think this was what Ruben was saying above.

**Comment by rubenhorn** [comment] 2022-01-07 16:49
closed by #157

**Closed by rubenhorn** 2022-01-07 16:49 UTC
Labels: bug
